### PR TITLE
fix: Fix #624 (edge cases when combining the box hashes)

### LINKED ISSUE #624: Bug: Error generating box hashes when the C2PA box is the first or last box
The current `BoxHash::generate_box_hash_from_stream` is setup to always assume there are boxes before AND after the C2PA box.

https://github.com/contentauth/c2pa-rs/blob/main/sdk/src/assertions/box_hash.rs#L240

### PR DESCRIPTION
**Pull request by brogdonm**
## Changes in this pull request

This addresses the issue #624 by only combining boxes that were found.

## Checklist
- [X] This PR represents a single feature, fix, or change.
- [X] All applicable changes have been documented.
- [X] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment.

### CODE REVIEW

**Comment by brogdonm** [comment]
@mauricefisher64 I updated the branch with the latest `main`. Thank you, sir.

**Comment by brogdonm** [comment]
@mauricefisher64 looking, this looks like something that is in the `main` branch already, the latest #677 PR has the same failing action.

**Comment by scouten-adobe** [comment]
@brogdonm @mauricefisher64 the "preflight" step is now failing whenever we have changes in two crates that need to be published at the same time. I will delete that step, but you can ignore that failure for now.

**Comment by scouten-adobe** [comment]
@brogdonm can you check the box that allows maintainers to update this branch (or update again yourself)? If so, I'll update with the fix for the errant CI step (#678, now merged) and land this PR based on @mauricefisher64's feedback.

I'm away from keyboard for about an hour but should be back to it circa 7pm US Pacific time.

**Comment by brogdonm** [comment]
> @brogdonm can you check the box that allows maintainers to update this branch (or update again yourself)? If so, I'll update with the fix for the errant CI step (#678, now merged) and land this PR based on @mauricefisher64's feedback.
> 
> I'm away from keyboard for about an hour but should be back to it circa 7pm US Pacific time.

Sorry, I was out the rest of the night last night. I'm not sure where the checkbox is, I saw this checkbox mentioned for others and I have looked for it, but I can't find it. I have followed various instructions online, but maybe I'm just overlooking it? I expected to see it here:

image


but I don't. Regardless, I have updated the branch.

**Review by scouten-adobe — APPROVED** [review]

**Comment by scouten-adobe** [comment]
Merging. Thank you @brogdonm!

**Pull request merged**
