### PR TITLE
Fix up some random typos.

### PR DESCRIPTION
**Pull request by brogdonm**
## Changes in this pull request
_Give a narrative description of what has been changed._

Noticed various typographic errors while perusing the SDK. Mostly in comments, but also a few places in code.

## Checklist
- [X] This PR represents a single feature, fix, or change.
- [X] All applicable changes have been documented.
- [ ] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment.

### CODE REVIEW

**Review by gpeacock — APPROVED** [review]

**Comment by mauricefisher64** [comment]
If this branch is brought up to date this PR is fine.

**Comment by brogdonm** [comment]
> If this branch is brought up to date this PR is fine.

I merged `main` into the branch and pushed.

**Comment by brogdonm** [comment]
@mauricefisher64 @gpeacock I just caught up with main again, I believe this is ready for review/merge.

**Comment by mauricefisher64** [comment]
Sorry about this but you will have to pull main again since we had to fix some build compatibility issues.

**Pull request merged**
