### PR TITLE
feat(sdk): Add support for MP3 without ID3 header

### PR DESCRIPTION
**Pull request by shc261392**
## Changes in this pull request

MP3 files does not necessarily have ID3 header and the current version will always raise "unsupported type" error when an file is MP3 format but has no ID3 header. Getting the ID3 header in MP3 file handler only serves the purpose of skipping the size of the header, hence when the MP3 file does not have an ID3 header, we could check for the MP3 header sync word (11 bits of 1) to make sure it is a valid MP3 file instead and skip 0 bytes as there is no ID3 header to skip.

This change would enable c2pa-rs to work with MP3 files that lack ID3 headers.

## Checklist
- [v] This PR represents a single feature, fix, or change.
- [v] All applicable changes have been documented.
- [v] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment.

### CODE REVIEW

**Comment by mauricefisher64** [comment]
Looks good.  If you bring the branch up to date with main I will merge.

**Review by mauricefisher64 — APPROVED** [review]
Thanks for the update

**Comment by mauricefisher64** [comment]
Can you please sign our contributor agreement:

https://github.com/contentauth/c2pa-rs/pull/588/checks?check_run_id=30903968016

**Comment by shc261392** [comment]
> Can you please sign our contributor agreement:
> 
> https://github.com/contentauth/c2pa-rs/pull/588/checks?check_run_id=30903968016

@mauricefisher64 I've signed it and closed/reopened the pull request to trigger the check again.

**Comment by scouten-adobe** [comment]
@shc261392 would you please enable maintainers' contributions? This would allow us to update to base branch and merge when we have a moment. Otherwise, we'll keep asking you to update and hope that we notice at the right time. 😐

**Comment by shc261392** [comment]
> @shc261392 would you please enable maintainers' contributions? This would allow us to update to base branch and merge when we have a moment. Otherwise, we'll keep asking you to update and hope that we notice at the right time. 😐

Sadly seems the option is [still not available for organization forks](https://github.com/orgs/community/discussions/5634). Seems I need to manually keep it updated.

**Comment by shc261392** [comment]
@mauricefisher64 Would you please check again to see if it could be merged?

**Comment by shc261392** [comment]
@mauricefisher64 @scouten-adobe I've created a pull request using personal repo fork instead so the maintainer editing option is enabled. It should make things easier: https://github.com/contentauth/c2pa-rs/pull/652

**Comment by shc261392** [comment]
Close to switch to personal fork for maintaining editing option. https://github.com/contentauth/c2pa-rs/pull/652

**Pull request closed without merging**
