### PR TITLE
(IGNORE) Disable cargo-semver-checks step

### PR DESCRIPTION
**Pull request by scouten-adobe**
Looks like there's a compatibility issue that needs resolving in cargo-semver-check crate.

Restore when https://github.com/obi1kenobi/cargo-semver-check/issues/122 is fixed.

### CODE REVIEW

**Comment by obi1kenobi** [comment]
As soon as the following workflow finishes (~5min), the issue will be fixed: 
https://github.com/obi1kenobi/cargo-semver-check/runs/8218166320

Apologies for the inconvenience.

**Review by gpeacock — APPROVED** [review]

**Comment by scouten-adobe** [comment]
@obi1kenobi looks like you're headed in the right direction, but your automated publish to crates.io appears to have failed.

**Comment by scouten-adobe** [comment]
Waiting now on https://github.com/obi1kenobi/cargo-semver-check/issues/124.

**Comment by obi1kenobi** [comment]
Apologies for the delay. I've published the new version and I'm taking steps to prevent the problem from happening again.

**Pull request merged**
