### PR TITLE
implement es256k support

### PR DESCRIPTION
**Pull request by iameli-streams**
This adds support for es256k signing (aka `secp256k1` or `NIST K-256`) signing alongside the existing es256 (aka `prime256v1` or `secp256r1` or `NIST P-256`) curve that we already have. This curve is widely used in cryptocurrencies and other web3 technologies, and there's a wide ecosystem of user-friendly hardware wallets, apps, and browser extensions that make use of the curve.

I know that a PR like this doesn't magically add it to the spec. I'll continue advocating for this change in a later version of the C2PA, but hopefully "it's too difficult to implement" can now be discounted as a reason :)

My pitch: convincing the world to get onboard with signed content is going to be hard enough without unnecessarily fragmenting our users. The Web3 community is already on-board with portable cryptographic identities. They'd love to embed those identities into content. They've got the means to do so. Are you really looking forward to explaining the distinction between the P-256 and K-256 curves to them, and explaining why they can't use those identities within the C2PA ecosystem because they're using the _wrong math_?

### CODE REVIEW

**Comment by iameli-streams** [comment]
Also a note: by _far_ the hardest part of this was generating new cert fixtures correctly. I finally figured out a script that can do it, so I figured I'd drop it here to save other people some pain. Just does ES for now, no RSA or ED25519.

```
#!/bin/bash

set -euo pipefail

# usage: be in c2pa-rs/sdk/tests/fixtures/certs, then:
# CURVE=secp256k1 NAME=es256k generate-c2pa-cert.sh

echo "curve=$CURVE name=$NAME"
temp="$(mktemp -d)"
cd $temp

openssl req \
  -new \
  -x509 \
  -nodes \
  -newkey ec:<(openssl ecparam -name $CURVE) \
  -extensions usr_cert \
  -extensions v3_req \
  -addext "subjectKeyIdentifier = hash" \
  -addext "authorityKeyIdentifier = keyid:always" \
  -addext basicConstraints=critical,CA:TRUE \
  -addext "keyUsage = critical,cRLSign,digitalSignature,keyCertSign" \
  -keyout root.pem \
  -out root.pub \
  -days 2920 -subj "/C=US/ST=CA/L=Somewhere/O=C2PA Test Root CA/OU=FOR TESTING_ONLY/CN=Root CA"

openssl x509 -inform pem -in root.pub -pubkey -noout > ${NAME}_root.pub_key

openssl req \
  -sha256 \
  -new \
  -nodes \
  -newkey ec:<(openssl ecparam -name $CURVE) \
  -keyout intermediate.pem \
  -out intermediate.csr \
  -extensions usr_cert \
  -extensions v3_req \
  -addext basicConstraints=critical,CA:TRUE \
  -addext "keyUsage = critical,cRLSign,digitalSignature,keyCertSign" \
  -subj '/C=US/ST=CA/L=Somewhere/O=C2PA Test Intermediate Root CA/OU=FOR TESTING_ONLY/CN=Intermediate CA'

openssl x509 \
  -req \
  -in intermediate.csr \
  -CA root.pub \
  -CAkey root.pem \
  -copy_extensions=copyall \
  -CAcreateserial \
  -out intermediate.crt

openssl req \
  -sha256 \
  -new \
  -nodes \
  -newkey ec:<(openssl ecparam -name $CURVE) \
  -keyout $NAME.pem \
  -out leaf.csr \
  -extensions usr_cert \
  -extensions v3_req \
  -addext "keyUsage = digitalSignature" \
  -addext "extendedKeyUsage = emailProtection" \
  -subj '/C=US/ST=CA/L=Somewhere/O=C2PA Test Signing Cert/OU=FOR TESTING_ONLY/CN=C2PA Signer'

openssl x509 \
  -req \
  -in leaf.csr \
  -CA intermediate.crt \
  -CAkey intermediate.pem \
  -copy_extensions=copyall \
  -CAcreateserial \
  -out leaf.crt

openssl x509 -in leaf.crt -out leaf.der -outform DER

openssl verify -CAfile root.pub -untrusted intermediate.crt leaf.crt

cd -
cat "$temp/leaf.crt" "$temp/intermediate.crt" > $NAME.pub
cp "$temp/${NAME}_root.pub_key" .
cp "$temp/$NAME.pem" .
openssl sha256 -binary "$temp/leaf.der" | openssl base64 >> trust/allowed_list.hash
cat "$temp/leaf.crt" >> trust/allowed_list.pem
echo "" >> trust/test_cert_root_bundle.pem
cat "$temp/root.pub" >> trust/test_cert_root_bundle.pem
rm -rf tmp
```

**Comment by gpeacock** [comment]
Thanks for doing all the work on this. As you said, we can't merge it until it becomes part of the spec, but nice to know it is ready.

**Comment by mauricefisher64** [comment]
We cannot support this until it is officially part of the C2PA spec.

**Comment by iameli** [comment]
Just showed back up here to rebase and didn't realize this had been closed outright. I get it, but just as an update we're quite close to shipping a version of Aquareum that allows for very easy livestreaming using es256k signing on my forked version of this library and it is my intention to keep it in sync.

I'll take the conversation about "so how many users do we need to have before it'd be weird not to have es256k signing" to other channels.

**Pull request closed without merging**
